# Generated by Django 4.2.18 on 2025-08-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerapplication',
            name='business_localization_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellerapplication',
            name='home_localization_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
