# Generated by Django 5.2.5 on 2025-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_firebase_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_request_reset_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
