from decouple import config


CHANNEL_LAYERS_DEFAULT_HOST = config('CHANNEL_LAYERS_DEFAULT_HOST', default='redis')
CHANNEL_LAYERS_DEFAULT_PORT = config('CHANNEL_LAYERS_DEFAULT_PORT', default=6379)
CELERY_BROKER_URL = f"redis://{CHANNEL_LAYERS_DEFAULT_HOST}:{CHANNEL_LAYERS_DEFAULT_PORT}/0"
