# Generated by Django 5.2.5 on 2025-08-11 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
