# Generated by Django 4.2.18 on 2025-08-21 11:18

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_reviewimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to=common.models.upload_to)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Position in the banner rotation')),
                ('start_datetime', models.DateTimeField(blank=True, null=True)),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this banner currently active?')),
            ],
            options={
                'ordering': ['position', '-created_at'],
                'indexes': [models.Index(fields=['position'], name='common_bann_positio_3e8c8e_idx')],
            },
        ),
    ]
