# Generated by Django 5.2.5 on 2025-09-02 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewimage',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
