# Generated by Django 5.2.5 on 2025-08-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_message_user_message_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
    ]
