# Generated by Django 4.2.18 on 2025-08-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderitem_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_cart_user_id_beaab2_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='orders_cart_product_81483c_idx',
        ),
    ]
