# Generated by Django 4.2.18 on 2025-08-23 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_cartitem_orders_cart_user_id_beaab2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_selected', to='orders.shippingaddress'),
        ),
    ]
