# Generated by Django 4.2.18 on 2025-08-23 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_selected_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='selected_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.shippingaddress'),
        ),
    ]
