# Generated by Django 4.2.18 on 2025-08-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_selected_shipping_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_shipping_address',
        ),
    ]
