# Generated by Django 5.2.5 on 2025-08-25 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_selected_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='selected_shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.shippingaddress'),
        ),
    ]
