# Generated by Django 5.2.5 on 2025-08-11 06:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='products/%Y/%m/%d/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary image used as thumbnail')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Optional SKU for inventory', max_length=64, null=True)),
                ('short_description', models.CharField(blank=True, max_length=500)),
                ('full_description', models.TextField(blank=True)),
                ('price1', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('option1', models.CharField(blank=True, max_length=100)),
                ('option2', models.CharField(blank=True, max_length=100)),
                ('option3', models.CharField(blank=True, max_length=100)),
                ('option4', models.CharField(blank=True, max_length=100)),
                ('is_stock', models.BooleanField(default=True)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('home_delivery', models.BooleanField(default=False)),
                ('pickup', models.BooleanField(default=False)),
                ('partner_delivery', models.BooleanField(default=False)),
                ('estimated_delivery_days', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, help_text='General availability toggle')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='common.category')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.seo')),
                ('tags', models.ManyToManyField(blank=True, related_name='products', to='common.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
