# Generated by Django 5.2.5 on 2025-08-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_seo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
