# Generated by Django 5.2.5 on 2025-08-13 08:12

import django.core.validators
import products.enums
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('discount_type', models.CharField(choices=products.enums.DiscountType.choices, default=products.enums.DiscountType['PERCENTAGE'], max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Enter percentage (0-100) for percentage discount or amount for flat discount.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(help_text='Select products this promotion applies to.', related_name='promotions', to='products.product')),
            ],
            options={
                'ordering': ['-start_datetime'],
                'indexes': [models.Index(fields=['name'], name='products_pr_name_71faae_idx'), models.Index(fields=['discount_type'], name='products_pr_discoun_472b6f_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='products_pr_start_d_95a061_idx')],
            },
        ),
    ]
