# Generated by Django 4.2.18 on 2025-08-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_method'),
        ('products', '0008_returnproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnproduct',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.orderitem'),
        ),
    ]
