# Generated by Django 5.2.5 on 2025-08-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
